Use hk patch-file when stashing in hooks
This avoids the following issue when committing havinf dirty changes
that are unstaged:
```
Error: failed to stash

Caused by:
    attempt to merge diffs created with conflicting options; class=Invalid (3)

Location:
    src/git.rs:420:18
```